# Generated by Django 4.2.2 on 2023-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_options_alter_recipe_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hexcolor',
            field=models.CharField(default='#ffffff', max_length=7, unique=True, verbose_name='Цветовой HEX-код'),
        ),
    ]
