# Generated by Django 4.2.2 on 2023-06-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredientinrecipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',), 'verbose_name': ('Ингредиент',), 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
